### ISSUE TITLE
Stark-Errors 👾

### ISSUE THREAD

**Issue by Naveen-X** [Naveen-X/Mr.Stark#26]
Error - Logs

**Comment by S4tyendra** [comment]
**Error in urlupload in url_upload:** 
 
 list index out of range
 
 **Complete Error:**
 Traceback (most recent call last):
   File "/home/ubuntu/Mr.Stark/Mr.Stark/Stark/__init__.py", line 100, in wrapper
     return await func(client, message, *args, kwargs)
   File "/home/ubuntu/Mr.Stark/Mr.Stark/Stark/Plugins/urlupload.py", line 151, in url_upload
     and not m.text.split(None, 1)[1]
 IndexError: list index out of range
 
 
 
 DATE: 2024-05-05 08:49:23.599906
 
 TIME: 08:49:23
 
 USER: 784589736
 
 USER MENTION: Viggu
 
 USERNAME: @ViGneSh_Leo
 
 FIRST NAME: Viggu
 
 CHAT: 784589736
 
 MESSAGE LINK: https://t.me/c/-1000784589736/10755 
 
 MESSAGE TEXT: /urlupload
 
 MESSAGE ID: 10755
 
 REPLIED TO MESSAGE ID: None
 
 REPLIED TO MESSAGE TEXT: None
 
 REPLIED TO MESSAGE USER ID: None
 
 REPLIED TO MESSAGE USER MENTION: None
 
 REPLIED TO MESSAGE USERNAME: @None
 
 REPLIED TO MESSAGE CHAT ID: None
 
 REPLIED TO MESSAGE LINK: None

**Comment by Hareshyadav4063** [comment]
> Error - Logs

Don't send me in email

**Comment by Hareshyadav** [comment]
Please don't mentioned me , remove my email.
